# Generated by Django 5.1.7 on 2025-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application_resume_alter_application_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="employer_notes",
            field=models.TextField(
                blank=True, help_text="Private notes for the employer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("cv_viewed", "CV Đã Xem"),
                    ("status_updated", "Trạng Thái Cập Nhật"),
                    ("application_submitted", "Đơn Ứng Tuyển Mới"),
                ],
                max_length=25,
            ),
        ),
    ]
