# Generated by Django 5.1.7 on 2025-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_application_employer_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(
                blank=True, help_text="Mức lương theo tháng (VNĐ)", null=True
            ),
        ),
    ]
