# Generated by Django 5.1.7 on 2025-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary",
        ),
        migrations.AddField(
            model_name="job",
            name="max_salary",
            field=models.IntegerField(
                blank=True, help_text="Mức lương tối đa theo tháng (VNĐ)", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="min_salary",
            field=models.IntegerField(
                blank=True, help_text="Mức lương tối thiểu theo tháng (VNĐ)", null=True
            ),
        ),
    ]
